FROM python:3-alpine

RUN mkdir NGramLangDetect
ADD NGramLangDetect/NGramLangDetectModel.py NGramLangDetect/
ADD NGramLangDetect/__init__.py NGramLangDetect/
ADD all_lang_data_model.pkl .
ADD ngram_lang_detect_run.py .

RUN apk add g++ libgomp && \
    pip3 install --upgrade pip && \
    pip3 install scikit-learn numpy && \
    pip3 cache purge && \
    apk del --purge g++

ENTRYPOINT python3 ngram_lang_detect_run.py all_lang_data_model.pkl
